config/routes.php
<?php

/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */

/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Home', 'action' => 'index']);
    $builder->connect('/login', ['controller' => 'Users', 'action' => 'login', 'prefix' => 'Member']);
    $builder->connect('/register', ['controller' => 'Users', 'action' => 'register', 'prefix' => 'Member']);
    $builder->connect('/logout', ['controller' => 'Users', 'action' => 'logout', 'prefix' => 'Member']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

$routes->prefix('Admin', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index', 'prefix' => 'Admin']);
    $routes->connect('/login', ['controller' => 'Users', 'action' => 'login', 'prefix' => 'Admin']);
    $routes->connect('/logout', ['controller' => 'Users', 'action' => 'logout', 'prefix' => 'Admin']);
    $routes->fallbacks(DashedRoute::class);
});

$routes->prefix('Member', function (RouteBuilder $routes) {
    $routes->connect('/', ['controller' => 'Books', 'action' => 'index', 'prefix' => 'Member']);
    $routes->connect('/register', ['controller' => 'Users', 'action' => 'register', 'prefix' => 'Member']);
    $routes->connect('/login', ['controller' => 'Users', 'action' => 'login', 'prefix' => 'Member']);
    $routes->connect('/logout', ['controller' => 'Users', 'action' => 'logout', 'prefix' => 'Member']);
    $routes->fallbacks(DashedRoute::class);
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Book.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Book Entity
 *
 * @property int $id
 * @property string $title
 * @property string $author
 * @property int $user_id
 * @property string $status
 * @property bool $view_by_standard
 * @property bool $view_by_verified
 * @property string $cover
 * @property string $amazon_url
 * @property \Cake\I18n\FrozenTime $date_added
 * @property \Cake\I18n\FrozenTime $date_updated
 *
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\BookCategory[] $book_categories
 * @property \App\Model\Entity\BookQuestionAnswer[] $book_question_answer
 * @property \App\Model\Entity\BookTag[] $book_tags
 */
class Book extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'title' => true,
        'author' => true,
        'user_id' => true,
        'status' => true,
        'view_by_standard' => true,
        'view_by_verified' => true,
        'cover' => true,
        'amazon_url' => true,
        'date_added' => true,
        'date_updated' => true,
        'user' => true,
        'book_categories' => true,
        'book_question_answer' => true,
        'book_tags' => true,
    ];
}

src/Model/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Model\Entity;

use Authentication\PasswordHasher\DefaultPasswordHasher;
use Cake\ORM\Entity;

/**
 * User Entity
 *
 * @property int $id
 * @property string $email
 * @property string $password
 * @property string $first_name
 * @property string $last_name
 * @property string $status
 * @property \Cake\I18n\FrozenTime $date_created
 */
class User extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'email' => true,
        'password' => true,
        'first_name' => true,
        'last_name' => true,
        'status' => true,
        'date_created' => true,
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password',
    ];

    protected function _setPassword(string $password): ?string
    {
        if (strlen($password) > 0) {
            return (new DefaultPasswordHasher())->hash($password);
        }
    }

    protected function _getFullName()
    {
        return ucfirst($this->first_name) . '  ' . ucfirst($this->last_name);
    }
}

src/Model/Table/BookCategoriesTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * BookCategories Model
 *
 * @property \App\Model\Table\BooksTable&\Cake\ORM\Association\BelongsTo $Books
 * @property \App\Model\Table\CategoriesTable&\Cake\ORM\Association\BelongsTo $Categories
 *
 * @method \App\Model\Entity\BookCategory newEmptyEntity()
 * @method \App\Model\Entity\BookCategory newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\BookCategory[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\BookCategory get($primaryKey, $options = [])
 * @method \App\Model\Entity\BookCategory findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\BookCategory patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\BookCategory[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\BookCategory|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\BookCategory saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\BookCategory[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\BookCategory[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\BookCategory[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\BookCategory[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class BookCategoriesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('book_categories');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->belongsTo('Books', [
            'foreignKey' => 'book_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['book_id'], 'Books'), ['errorField' => 'book_id']);
        $rules->add($rules->existsIn(['category_id'], 'Categories'), ['errorField' => 'category_id']);

        return $rules;
    }
}

src/Controller/Member/AppController.php
<?php

declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */

namespace App\Controller\Member;

use Cake\Controller\Controller;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Authentication.Authentication');

        $this->viewBuilder()->setLayout('member');

        /*
         * Enable the following component for recommended CakePHP form protection settings.
         * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
         */
        //$this->loadComponent('FormProtection');
    }
}

src/Controller/Member/UsersController.php
<?php

declare(strict_types=1);

namespace App\Controller\Member;

use App\Controller\Member\AppController;

/**
 * Users Controller
 *
 * @method \App\Model\Entity\User[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class UsersController extends AppController
{
    public function beforeFilter(\Cake\Event\EventInterface $event)
    {
        parent::beforeFilter($event);
        // Configure the login action to not require authentication, preventing
        // the infinite redirect loop issue
        $this->Authentication->addUnauthenticatedActions(['login', 'register', 'forgot']);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $users = $this->paginate($this->Users);

        $this->set(compact('users'));
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => [],
        ]);

        $this->set(compact('user'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $user = $this->Users->newEmptyEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set(compact('user'));
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => [],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set(compact('user'));
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function register()
    {
        $user = $this->Users->newEmptyEntity();
        if ($this->request->is('post')) {
            $raw = $this->request->getData();
            $raw['status'] = 1;
            $user = $this->Users->patchEntity($user, $raw);
            if ($this->Users->save($user)) {
                $this->Authentication->setIdentity($user);
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Registration could not be saved. Please, try again.'));
        }
        $this->set(compact('user'));
    }

    public function login()
    {
        $this->request->allowMethod(['get', 'post']);
        $result = $this->Authentication->getResult();
        // regardless of POST or GET, redirect if user is logged in
        if ($result->isValid()) {
            // redirect to /articles after login success
            $user = $this->Authentication->getIdentity();

            $redirect = $this->request->getQuery('redirect', [
                'action' => 'index',
            ]);

            return $this->redirect($redirect);
        }

        // display error if user submitted and authentication failed
        if ($this->request->is('post') && !$result->isValid()) {
            $this->Flash->error(__('Invalid username or password'));
        }
    }

    public function logout()
    {
        $result = $this->Authentication->getResult();
        // regardless of POST or GET, redirect if user is logged in
        if ($result->isValid()) {
            $this->Authentication->logout();
            return $this->redirect(['controller' => 'Users', 'action' => 'login', 'prefix' => 'Member']);
        }
    }
}

templates/Member/Books/add.php
<?php

/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $book
 */
?>

<div class="books form px-10">
    <div class="py-8 max-w-2xl mx-auto">

        <div class="flex justify-between align-middle">
            <h2 class="text-2xl font- text-cool-gray-600 leading-tight"><?= __('Add Book') ?></h2>
            <div class="flex-inline mr-2">
                <?= $this->Html->link(__('List Books'), ['action' => 'index'], ['class' => 'bg-transparent hover:bg-green-500 text-green-900 text-sm font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded']) ?>
            </div>
        </div>

        <div class="mt-8 pt-8 border-t border-gray-400 overflow-x-auto">
            <?= $this->Form->create($book, ['enctype' => 'multipart/form-data']) ?>
            <div class='flex flex-wrap mb-6'>
                <?php
                echo $this->Form->control('user_id', ['options' => $users]);
                echo $this->Form->control('title');
                echo $this->Form->control('author');
                echo $this->Form->control('amazon_url');
                echo $this->Form->control('book_categories', ['options' => $categories,'multiple' => true, 'label' => 'Book Categories (Select Multiple)']);
                echo $this->Form->control('book_tags', ['label' => 'Tags (Separated by comma)','placeholder' => 'Enter Tags']);

                echo $this->Form->control('coverTmp', [
                    'type' => 'file',
                    'label' => 'Cover Image'
                ]);
                echo $this->Form->control('status');
                ?>
                <h3 class="border-b border-cool-gray-300 block w-full pb-3 mb-5 mt-5 text-cool-gray-500">Additional Information</h3>
                <?php foreach ($questions as $k => $v): ?>
                    <?php if ($v->type == 'text'): ?>
                        <div class="relative w-full appearance-none label-floating mb-3 textarea required">
                            <textarea class="tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full bg-cool-gray-100 border border-cool-gray-200 rounded focus:outline-none focus:bg-white focus:border-gray-500" name="question[<?= $v->id ?>][answer]" required="required" id="question" rows="5"></textarea>
                            <label class="absolute tracking-wide py-2 px-4 mb-4 hidden leading-tight top-0 left-0 cursor-text"><?= $v->question ?></label>
                        </div>
                    <?php else: ?>
                        <div class="mb-3"><?= ucfirst($v->question) ?></div>
                        <div class="grid grid-flow-row w-full grid-cols-2 mb-5 grid-row-2 gap-4">
                        <?php foreach ($v->question_choices as $x => $y): ?>
                            <div>
                                <div class="relative w-full appearance-none label-floating mb-3 checkbox"><label for="questionChoice-<?= $k.'-'.$x ?>" class="inline-flex items-center"><input type="checkbox" name="question[<?= $v->id ?>][answer][]" class="form-checkbox" value="<?= $y->name ?>" id="questionChoice-<?= $k.'-'.$x ?>"> <span class="ml-2"><?= $y->name ?></span></label></div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                        
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <input type="submit" value="Submit" class="bg-transparent cursor-pointer float-right hover:bg-blue-500 text-blue-900 font-semibold hover:text-white py-2 px-6 border border-blue-500 hover:border-transparent rounded">
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Member/Books/edit.php
<?php

/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $book
 */
?>

<div class="books form px-10">
    <div class="py-8 max-w-2xl mx-auto">

        <div class="flex justify-between align-middle">
            <h2 class="text-2xl font- text-cool-gray-600 leading-tight"><?= __('Edit Book') ?></h2>
            <div class="flex-inline mr-2">
                <?= $this->Form->postLink(
    __('Delete'),
    ['action' => 'delete', $book->id],
    ['confirm' => __('Are you sure you want to delete this record?'), 'class' => 'bg-transparent hover:bg-red-500 text-red-900 text-sm font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded']
) ?>
                <?= $this->Html->link(__('List Books'), ['action' => 'index'], ['class' => 'bg-transparent hover:bg-green-500 text-green-900 text-sm font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded']) ?>
            </div>
        </div>

        <div class="mt-8 pt-8 border-t border-gray-400 overflow-x-auto">
            <?= $this->Form->create($book, ['enctype' => 'multipart/form-data']) ?>
            <div class='flex flex-wrap mb-6'>
                <?php
                echo $this->Form->control('user_id', ['options' => $users]);
                echo $this->Form->control('title');
                echo $this->Form->control('author');
                echo $this->Form->control('amazon_url');
                echo $this->Form->control('book_categories', ['options' => $categories,'multiple' => true, 'label' => 'Book Categories (Select Multiple)']);
                echo $this->Form->control('book_tags', ['label' => 'Tags (Separated by comma)','placeholder' => 'Enter Tags']);

                echo $this->Form->control('coverTmp', [
                    'type' => 'file',
                    'label' => 'Cover Image'
                ]);
                echo $this->Form->control('status');
                ?>
                <h3 class="border-b border-cool-gray-300 block w-full pb-3 mb-5 mt-5 text-cool-gray-500">Additional Information</h3>
                <?php foreach ($questions as $k => $v): ?>
                    <?php if ($v->type == 'text'): ?>
                        <div class="relative w-full appearance-none label-floating mb-3 textarea required">
                            <textarea class="tracking-wide py-2 px-4 mb-3 leading-relaxed appearance-none block w-full bg-cool-gray-100 border border-cool-gray-200 rounded focus:outline-none focus:bg-white focus:border-gray-500" name="question[<?= $v->id ?>][answer]" required="required" id="question" rows="5"><?= ($v->book_question_answer[0]) ? $v->book_question_answer[0]->answer : "" ?></textarea>
                            <label class="absolute tracking-wide py-2 px-4 mb-4 hidden leading-tight top-0 left-0 cursor-text"><?= $v->question ?></label>
                        </div>
                    <?php else: ?>
                        <div class="mb-3"><?= ucfirst($v->question) ?></div>
                        <div class="grid grid-flow-row w-full grid-cols-2 mb-5 grid-row-2 gap-4">
                        <?php foreach ($v->question_choices as $x => $y): ?>
                            <div>
                                <div class="relative w-full appearance-none label-floating mb-3 checkbox"><label for="questionChoice-<?= $k.'-'.$x ?>" class="inline-flex items-center"><input type="checkbox" name="question[<?= $v->id ?>][answer][]" class="form-checkbox" <?= (strpos($v->book_question_answer[0]->answer, $y->name) !== false) ? "checked" : "" ?> value="<?= $y->name ?>" id="questionChoice-<?= $k.'-'.$x ?>"> <span class="ml-2"><?= $y->name ?></span></label></div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                        
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <input type="submit" value="Submit" class="bg-transparent cursor-pointer float-right hover:bg-blue-500 text-blue-900 font-semibold hover:text-white py-2 px-6 border border-blue-500 hover:border-transparent rounded">
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Member/Books/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface $book
 */
?>
<div class="px-10 py-8 w-full">

    <div class="flex justify-between align-center mb-8">
        <h2 class="text-2xl font- text-cool-gray-400 leading-tight"><?= __('Book ID #'.$book->id) ?></h2>
        <div class="flex-inline mr-2">
            <?= $this->Html->link(__('Edit Book'), ['action' => 'edit', $book->id], ['class' => 'bg-transparent hover:bg-orange-500 text-orange-900 text-sm font-semibold hover:text-white py-2 px-4 border border-orange-500 hover:border-transparent rounded']) ?>
        <?= $this->Form->postLink(__('Delete Book'), ['action' => 'delete', $book->id], ['confirm' => __('Are you sure you want to delete # {0}?', $book->id), 'class' => 'bg-transparent hover:bg-red-500 text-red-900 text-sm font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded']) ?>
        <?= $this->Html->link(__('List Books'), ['action' => 'index'], ['class' => 'bg-transparent hover:bg-blue-500 text-blue-900 text-sm font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded']) ?>
        <?= $this->Html->link(__('New Book'), ['action' => 'add'], ['class' => 'bg-transparent hover:bg-green-500 text-green-900 text-sm font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded']) ?>
        </div>
    </div>

    <div class="flex">
        <div class="w-1/4">
            <img class="w-full" src="<?=  DS . 'book_covers' . DS . $book->cover ?>" onerror="this.src='<?=  DS . 'book_covers' . DS . 'default_book_cover' ?>'" alt="">
        </div>
        <div class="flex-1 pl-10 pt-5">
            <h1 class="text-xl font-semibold"><?= h($book->title) ?></h1>
            <h2 class="text-cool-gray-700"><?= h($book->author) ?></h2>
            <a href="<?= h($book->amazon_url) ?>" class="inline-block text-white rounded-sm px-3 py-1 mt-3 text-sm border border-blue-700 bg-blue-500" target="_blank">Amazon Link</a>
            <div class="mt-5 border-t pt-5">
                <div class="mb-3">
                    <span class="block text-sm text-cool-gray-500 font-light">Category</span>
                    <div class="inline-flex">
                        <?php foreach ($book->book_categories as $category): ?>
                            <a href="#" class="mr-2 underline text-orange-400"> <?= $category->category->name ?> </a>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="mb-3">
                    <span class="block text-sm text-cool-gray-500 font-light">Tags</span>
                    <div class="inline-flex">
                        <?php foreach ($book->book_tags as $tag): ?>
                            <a href="#" class="mr-2 underline text-orange-400"> <?= $tag->name ?> </a>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="flex mb-3">
                    <div>
                        <span class="block text-sm text-cool-gray-500 font-light">Publisher</span>
                        <?= h($book->user->full_name) ?>
                    </div>
                    <div class="ml-10">
                        <span class="block text-sm text-cool-gray-500 font-light">Status</span>
                        <?= h($book->status ? 'Active' : 'Inactive') ?>
                    </div>
                    <div class="ml-10">
                        <span class="block text-sm text-cool-gray-500 font-light">Date Added</span>
                        <?= h($book->date_added) ?>
                    </div>
                    <div class="ml-10">
                        <span class="block text-sm text-cool-gray-500 font-light">Date Updated</span>
                        <?= h($book->date_updated) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h2 class="text-cool-gray-400 border-b border-cool-gray-300 pb-3 mb-5 mt-5">Additional Information</h2>
    <div class="grid grid-flow-row w-full grid-cols-2 grid-row-2 gap-5">
        <?php foreach ($book->book_question_answer as $k => $v): ?>
            <div class="mb-5">
                <div class="text-cool-gray-400 mb-1"><?= $v->question->question ?></div>
                <?php if ($v->question->type == 'selection'): ?>
                    <ul class="list-disc ml-10">
                    <?php
                        $answers = explode('|', $v->answer);
                        foreach ($answers as $x => $y):
                    ?>
                        <li><?= $y ?></li>
                    <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <div><?= $v->answer ?></div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>